all: xdone

git-dir := $(realpath ../.. | tr -d '\n')
nproc := $(shell nproc)

xdone: meson.build version.sh
	rm -rf build
	mkdir -p build
	mkdir -p ${git-dir}/.xopt
	true &&                                                 \
		cd build &&                                         \
		cmake .. -DCMAKE_INSTALL_PREFIX=${git-dir}/.xopt && \
		make libcork-static -j${nproc} &&                   \
		make install &&                                     \
		cd .. && touch xdone

